/**
 * Mirrors the shape returned by the `metadata` API endpoint.
 * All fields are optional to allow graceful degradation when
 * the API is unavailable or the payload is partially missing.
 */
export interface PageMeta {
  meta_title?: string;
  meta_keywords?: string;
  meta_description?: string;
}

export interface SiteMetadata {
  site?: {
    title?: string;
    name?: string;
    /** Usually empty from the CMS — canonical URLs are generated by Next.js */
    canonical_url?: string;
  };
  home_meta?: PageMeta;
  /**
   * Keys match CMS page names: "services" | "gallery" | "testimonial"
   * | "blog" | "faq" | "contact"
   */
  pages_meta?: Record<string, PageMeta>;
  social?: {
    fb_img?: string;
    x_img?: string;
    og_type?: string;
  };
  scripts?: {
    google_analytics?: string;
    fb_pixel?: string;
    schema_code?: string | null;
    robots?: {
      index?: boolean;
      follow?: boolean;
    };
  };
}

/** Keys that exist under `pages_meta` in the API response */
export type PageMetaKey =
  | "home"
  | "services"
  | "gallery"
  | "testimonial"
  | "blog"
  | "faq"
  | "contact";
